// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Scratch fixture: a minimal Starlight site whose single page is generated by a
// Node-only prebuild (scripts/gen-rules.mjs). No `site:` custom domain -- this
// never deploys; it exists only to prove the reusable deploy-site.yml build +
// `prebuild` seam works with no Python leg (python-version: "").
export default defineConfig({
	integrations: [
		starlight({
			title: 'deploy-site fixture',
			description:
				'Node-only prebuild proof for the reusable deploy-site.yml workflow.',
		}),
	],
});
